name: Require Code Review Before Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request a Reviewer
        uses: hmarr/auto-approve-action@v3
        with:
          reviewers: 'timothy.hobbs.kumah@gmail.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  enforce-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Approved Reviews
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const approved = reviews.some(review => review.state === "APPROVED");

            if (!approved) {
              core.setFailed("At least one approval is required before merging.");
            }
